function seqs = configSeqsNew(dataset_path)

seqUAV123_10fps = {struct('name','bike1','path',fullfile(dataset_path, 'bike1\'),'startFrame',1,'endFrame',1029,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
    struct('name','bike2','path',fullfile(dataset_path, 'bike2\'),'startFrame',1,'endFrame',185,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
    struct('name','bike3','path',fullfile(dataset_path, 'bike3\'),'startFrame',1,'endFrame',145,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
    struct('name','person3_s','path',fullfile(dataset_path, 'person3_s\'),'startFrame',1,'endFrame',169,'nz',6,'ext','jpg','init_rect', [0,0,0,0])}; % added by Holy 1903071103
%     struct('name','bird1_1','path',fullfile(dataset_path, 'bird1\'),'startFrame',1,'endFrame',85,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','bird1_2','path',fullfile(dataset_path, 'bird1\'),'startFrame',259,'endFrame',493,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','bird1_3','path',fullfile(dataset_path, 'bird1\'),'startFrame',525,'endFrame',813,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','boat1','path',fullfile(dataset_path, 'boat1\'),'startFrame',1,'endFrame',301,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','boat2','path',fullfile(dataset_path, 'boat2\'),'startFrame',1,'endFrame',267,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','boat3','path',fullfile(dataset_path, 'boat3\'),'startFrame',1,'endFrame',301,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','boat4','path',fullfile(dataset_path, 'boat4\'),'startFrame',1,'endFrame',185,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','boat5','path',fullfile(dataset_path, 'boat5\'),'startFrame',1,'endFrame',169,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','boat6','path',fullfile(dataset_path, 'boat6\'),'startFrame',1,'endFrame',269,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','boat7','path',fullfile(dataset_path, 'boat7\'),'startFrame',1,'endFrame',179,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','boat8','path',fullfile(dataset_path, 'boat8\'),'startFrame',1,'endFrame',229,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','boat9','path',fullfile(dataset_path, 'boat9\'),'startFrame',1,'endFrame',467,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','building1','path',fullfile(dataset_path, 'building1\'),'startFrame',1,'endFrame',157,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','building2','path',fullfile(dataset_path, 'building2\'),'startFrame',1,'endFrame',193,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','building3','path',fullfile(dataset_path, 'building3\'),'startFrame',1,'endFrame',277,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','building4','path',fullfile(dataset_path, 'building4\'),'startFrame',1,'endFrame',263,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','building5','path',fullfile(dataset_path, 'building5\'),'startFrame',1,'endFrame',161,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car1_1','path',fullfile(dataset_path, 'car1\'),'startFrame',1,'endFrame',251,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car1_2','path',fullfile(dataset_path, 'car1\'),'startFrame',251,'endFrame',543,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car1_3','path',fullfile(dataset_path, 'car1\'),'startFrame',543,'endFrame',877,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car2','path',fullfile(dataset_path, 'car2\'),'startFrame',1,'endFrame',441,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car3','path',fullfile(dataset_path, 'car3\'),'startFrame',1,'endFrame',573,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car4','path',fullfile(dataset_path, 'car4\'),'startFrame',1,'endFrame',449,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car5','path',fullfile(dataset_path, 'car5\'),'startFrame',1,'endFrame',249,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car6_1','path',fullfile(dataset_path, 'car6\'),'startFrame',1,'endFrame',163,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car6_2','path',fullfile(dataset_path, 'car6\'),'startFrame',163,'endFrame',603,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car6_3','path',fullfile(dataset_path, 'car6\'),'startFrame',603,'endFrame',985,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car6_4','path',fullfile(dataset_path, 'car6\'),'startFrame',985,'endFrame',1309,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car6_5','path',fullfile(dataset_path, 'car6\'),'startFrame',1309,'endFrame',1621,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car7','path',fullfile(dataset_path, 'car7\'),'startFrame',1,'endFrame',345,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car8_1','path',fullfile(dataset_path, 'car8\'),'startFrame',1,'endFrame',453,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car8_2','path',fullfile(dataset_path, 'car8\'),'startFrame',453,'endFrame',859,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car9','path',fullfile(dataset_path, 'car9\'),'startFrame',1,'endFrame',627,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car10','path',fullfile(dataset_path, 'car10\'),'startFrame',1,'endFrame',469,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car11','path',fullfile(dataset_path, 'car11\'),'startFrame',1,'endFrame',113,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car12','path',fullfile(dataset_path, 'car12\'),'startFrame',1,'endFrame',167,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car13','path',fullfile(dataset_path, 'car13\'),'startFrame',1,'endFrame',139,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car14','path',fullfile(dataset_path, 'car14\'),'startFrame',1,'endFrame',443,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car15','path',fullfile(dataset_path, 'car15\'),'startFrame',1,'endFrame',157,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car16_1','path',fullfile(dataset_path, 'car16\'),'startFrame',1,'endFrame',139,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car16_2','path',fullfile(dataset_path, 'car16\'),'startFrame',139,'endFrame',665,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car17','path',fullfile(dataset_path, 'car17\'),'startFrame',1,'endFrame',353,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car18','path',fullfile(dataset_path, 'car18\'),'startFrame',1,'endFrame',403,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','group1_1','path',fullfile(dataset_path, 'group1\'),'startFrame',1,'endFrame',445,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','group1_2','path',fullfile(dataset_path, 'group1\'),'startFrame',445,'endFrame',839,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','group1_3','path',fullfile(dataset_path, 'group1\'),'startFrame',839,'endFrame',1309,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','group1_4','path',fullfile(dataset_path, 'group1\'),'startFrame',1309,'endFrame',1625,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','group2_1','path',fullfile(dataset_path, 'group2\'),'startFrame',1,'endFrame',303,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','group2_2','path',fullfile(dataset_path, 'group2\'),'startFrame',303,'endFrame',591,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','group2_3','path',fullfile(dataset_path, 'group2\'),'startFrame',591,'endFrame',895,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','group3_1','path',fullfile(dataset_path, 'group3\'),'startFrame',1,'endFrame',523,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','group3_2','path',fullfile(dataset_path, 'group3\'),'startFrame',523,'endFrame',943,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','group3_3','path',fullfile(dataset_path, 'group3\'),'startFrame',943,'endFrame',1457,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','group3_4','path',fullfile(dataset_path, 'group3\'),'startFrame',1457,'endFrame',1843,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person1','path',fullfile(dataset_path, 'person1\'),'startFrame',1,'endFrame',267,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person2_1','path',fullfile(dataset_path, 'person2\'),'startFrame',1,'endFrame',397,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person2_2','path',fullfile(dataset_path, 'person2\'),'startFrame',397,'endFrame',875,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person3','path',fullfile(dataset_path, 'person3\'),'startFrame',1,'endFrame',215,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person4_1','path',fullfile(dataset_path, 'person4\'),'startFrame',1,'endFrame',501,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person4_2','path',fullfile(dataset_path, 'person4\'),'startFrame',501,'endFrame',915,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person5_1','path',fullfile(dataset_path, 'person5\'),'startFrame',1,'endFrame',293,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person5_2','path',fullfile(dataset_path, 'person5\'),'startFrame',293,'endFrame',701,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person6','path',fullfile(dataset_path, 'person6\'),'startFrame',1,'endFrame',301,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person7_1','path',fullfile(dataset_path, 'person7\'),'startFrame',1,'endFrame',417,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person7_2','path',fullfile(dataset_path, 'person7\'),'startFrame',417,'endFrame',689,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person8_1','path',fullfile(dataset_path, 'person8\'),'startFrame',1,'endFrame',359,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person8_2','path',fullfile(dataset_path, 'person8\'),'startFrame',359,'endFrame',509,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person9','path',fullfile(dataset_path, 'person9\'),'startFrame',1,'endFrame',221,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person10','path',fullfile(dataset_path, 'person10\'),'startFrame',1,'endFrame',341,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person11','path',fullfile(dataset_path, 'person11\'),'startFrame',1,'endFrame',241,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person12_1','path',fullfile(dataset_path, 'person12\'),'startFrame',1,'endFrame',201,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person12_2','path',fullfile(dataset_path, 'person12\'),'startFrame',201,'endFrame',541,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person13','path',fullfile(dataset_path, 'person13\'),'startFrame',1,'endFrame',295,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person14_1','path',fullfile(dataset_path, 'person14\'),'startFrame',1,'endFrame',283,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person14_2','path',fullfile(dataset_path, 'person14\'),'startFrame',283,'endFrame',605,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person14_3','path',fullfile(dataset_path, 'person14\'),'startFrame',605,'endFrame',975,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person15','path',fullfile(dataset_path, 'person15\'),'startFrame',1,'endFrame',447,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person16','path',fullfile(dataset_path, 'person16\'),'startFrame',1,'endFrame',383,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person17_1','path',fullfile(dataset_path, 'person17\'),'startFrame',1,'endFrame',501,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person17_2','path',fullfile(dataset_path, 'person17\'),'startFrame',501,'endFrame',783,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person18','path',fullfile(dataset_path, 'person18\'),'startFrame',1,'endFrame',465,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person19_1','path',fullfile(dataset_path, 'person19\'),'startFrame',1,'endFrame',415,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person19_2','path',fullfile(dataset_path, 'person19\'),'startFrame',415,'endFrame',931,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person19_3','path',fullfile(dataset_path, 'person19\'),'startFrame',931,'endFrame',1453,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person20','path',fullfile(dataset_path, 'person20\'),'startFrame',1,'endFrame',595,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person21','path',fullfile(dataset_path, 'person21\'),'startFrame',1,'endFrame',163,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person22','path',fullfile(dataset_path, 'person22\'),'startFrame',1,'endFrame',67,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','person23','path',fullfile(dataset_path, 'person23\'),'startFrame',1,'endFrame',133,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','truck1','path',fullfile(dataset_path, 'truck1\'),'startFrame',1,'endFrame',155,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','truck2','path',fullfile(dataset_path, 'truck2\'),'startFrame',1,'endFrame',129,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','truck3','path',fullfile(dataset_path, 'truck3\'),'startFrame',1,'endFrame',179,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','truck4_1','path',fullfile(dataset_path, 'truck4\'),'startFrame',1,'endFrame',193,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','truck4_2','path',fullfile(dataset_path, 'truck4\'),'startFrame',193,'endFrame',421,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','uav1_1','path',fullfile(dataset_path, 'uav1\'),'startFrame',1,'endFrame',519,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','uav1_2','path',fullfile(dataset_path, 'uav1\'),'startFrame',519,'endFrame',793,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','uav1_3','path',fullfile(dataset_path, 'uav1\'),'startFrame',825,'endFrame',1157,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','uav2','path',fullfile(dataset_path, 'uav2\'),'startFrame',1,'endFrame',45,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','uav3','path',fullfile(dataset_path, 'uav3\'),'startFrame',1,'endFrame',89,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','uav4','path',fullfile(dataset_path, 'uav4\'),'startFrame',1,'endFrame',53,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','uav5','path',fullfile(dataset_path, 'uav5\'),'startFrame',1,'endFrame',47,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','uav6','path',fullfile(dataset_path, 'uav6\'),'startFrame',1,'endFrame',37,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','uav7','path',fullfile(dataset_path, 'uav7\'),'startFrame',1,'endFrame',125,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','uav8','path',fullfile(dataset_path, 'uav8\'),'startFrame',1,'endFrame',101,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','wakeboard1','path',fullfile(dataset_path, 'wakeboard1\'),'startFrame',1,'endFrame',141,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','wakeboard2','path',fullfile(dataset_path, 'wakeboard2\'),'startFrame',1,'endFrame',245,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','wakeboard3','path',fullfile(dataset_path, 'wakeboard3\'),'startFrame',1,'endFrame',275,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','wakeboard4','path',fullfile(dataset_path, 'wakeboard4\'),'startFrame',1,'endFrame',233,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','wakeboard5','path',fullfile(dataset_path, 'wakeboard5\'),'startFrame',1,'endFrame',559,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','wakeboard6','path',fullfile(dataset_path, 'wakeboard6\'),'startFrame',1,'endFrame',389,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','wakeboard7','path',fullfile(dataset_path, 'wakeboard7\'),'startFrame',1,'endFrame',67,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','wakeboard8','path',fullfile(dataset_path, 'wakeboard8\'),'startFrame',1,'endFrame',515,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','wakeboard9','path',fullfile(dataset_path, 'wakeboard9\'),'startFrame',1,'endFrame',119,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','wakeboard10','path',fullfile(dataset_path, 'wakeboard10\'),'startFrame',1,'endFrame',157,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
%     struct('name','car1_s','path',fullfile(dataset_path, 'car1_s\'),'startFrame',1,'endFrame',492,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','car2_s','path',fullfile(dataset_path, 'car2_s\'),'startFrame',1,'endFrame',107,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','car3_s','path',fullfile(dataset_path, 'car3_s\'),'startFrame',1,'endFrame',434,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','car4_s','path',fullfile(dataset_path, 'car4_s\'),'startFrame',1,'endFrame',277,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','person1_s','path',fullfile(dataset_path, 'person1_s\'),'startFrame',1,'endFrame',534,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','person2_s','path',fullfile(dataset_path, 'person2_s\'),'startFrame',1,'endFrame',84,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','person3_s','path',fullfile(dataset_path, 'person3_s\'),'startFrame',1,'endFrame',169,'nz',6,'ext','jpg','init_rect', [0,0,0,0])};

seqs = seqUAV123_10fps;
end
